# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Minecraft版本
minecraft_version=26.1.2
# Fabric Loader
loader_version=0.16.9
# Fabric API版本（适配1.21.2）
fabric_api_version=0.102.1+1.21.2
# ModMenu版本（适配1.21.2）
modmenu_version=11.0.0
# 你的模组信息
maven_group=com.ltcg
mod_id=modmenuwebaddon
mod_version=1.0.1
archives_base_name=modmenu-web-addon
